export const AUTH_USER_REPOSITORY = Symbol('AUTH_USER_REPOSITORY');
export const REFRESH_TOKEN_REPOSITORY = Symbol('REFRESH_TOKEN_REPOSITORY');
export const PASSWORD_SERVICE = Symbol('PASSWORD_SERVICE');
export const TOKEN_SERVICE = Symbol('TOKEN_SERVICE');
export const AUTH_USECASES = Symbol('AUTH_USECASE');
