export const MENTOR_REPOSITORY_TOKEN = Symbol('MENTOR_REPOSITORY_TOKEN');
export const CREATE_MENTOR_USECASE = Symbol('CREATE_MENTOR_USECASE');
export const UPDATE_MENTOR_USECASE = Symbol('UPDATE_MENTOR_USECASE');
export const GET_MENTOR_USECASE = Symbol('GET_MENTOR_USECASE');
export const APPROVE_MENTOR_USECASE = Symbol('APPROVE_MENTOR_USECASE');
export const REJECT_MENTOR_USECASE = Symbol('REJECT_MENTOR_USECASE');
export const REQUEST_MENTOR_CORRECTION_USECASE = Symbol(
  'REQUEST_MENTOR_CORRECTION_USECASE ',
);
