export enum ErrorCode {
  // Common
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  UNAUTHORIZED = 'UNAUTHORIZED',
  FORBIDDEN = 'FORBIDDEN',

  // User
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  USER_ALREADY_EXISTS = 'USER_ALREADY_EXISTS',
  USER_BLOCKED = 'USER_BLOCKED',

  // Auth
  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
  TOKEN_EXPIRED = 'TOKEN_EXPIRED',
  TOKEN_INVALID = 'TOKEN_INVALID',

  // Mentor
  MENTOR_NOT_FOUND = 'MENTOR_NOT_FOUND',
  MENTOR_NOT_APPROVED = 'MENTOR_NOT_APPROVED',

  // Admin
  ADMIN_NOT_FOUND = 'ADMIN_NOT_FOUND',
  ACTION_NOT_ALLOWED = 'ACTION_NOT_ALLOWED',
}
