/**
 * Centralized error codes for consistent error handling across the application
 */
export enum ErrorCode {
  // Authentication & Authorization (40x)
  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  EMAIL_NOT_VERIFIED = 'EMAIL_NOT_VERIFIED',
  INSUFFICIENT_PERMISSIONS = 'INSUFFICIENT_PERMISSIONS',
  TOKEN_EXPIRED = 'TOKEN_EXPIRED',
  TOKEN_INVALID = 'TOKEN_INVALID',
  TOKEN_REVOKED = 'TOKEN_REVOKED',
  UNAUTHORIZED = 'UNAUTHORIZED',
  FORBIDDEN = 'FORBIDDEN',

  // Validation (400)
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  VALIDATION_FAILED = 'VALIDATION_FAILED',
  INVALID_EMAIL = 'INVALID_EMAIL',
  INVALID_PASSWORD = 'INVALID_PASSWORD',
  INVALID_ID_FORMAT = 'INVALID_ID_FORMAT',

  // Resources (40x)
  RESOURCE_NOT_FOUND = 'RESOURCE_NOT_FOUND',
  RESOURCE_ALREADY_EXISTS = 'RESOURCE_ALREADY_EXISTS',
  RESOURCE_CONFLICT = 'RESOURCE_CONFLICT',

  // User-specific
  USER_ALREADY_EXISTS = 'USER_ALREADY_EXISTS',
  USER_BLOCKED = 'USER_BLOCKED',

  // Mentor-specific
  MENTOR_NOT_FOUND = 'MENTOR_NOT_FOUND',
  MENTOR_NOT_APPROVED = 'MENTOR_NOT_APPROVED',

  // Admin-specific
  ADMIN_NOT_FOUND = 'ADMIN_NOT_FOUND',
  ACTION_NOT_ALLOWED = 'ACTION_NOT_ALLOWED',

  // Operations (40x-50x)
  OPERATION_FAILED = 'OPERATION_FAILED',
  INVALID_OPERATION = 'INVALID_OPERATION',

  // External Services (50x)
  EMAIL_SERVICE_FAILED = 'EMAIL_SERVICE_FAILED',
  FILE_UPLOAD_FAILED = 'FILE_UPLOAD_FAILED',
  EXTERNAL_SERVICE_ERROR = 'EXTERNAL_SERVICE_ERROR',

  // Rate Limiting (429)
  TOO_MANY_REQUESTS = 'TOO_MANY_REQUESTS',
  RATE_LIMIT_EXCEEDED = 'RATE_LIMIT_EXCEEDED',

  // Server (50x)
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
  SERVICE_UNAVAILABLE = 'SERVICE_UNAVAILABLE',
  DATABASE_ERROR = 'DATABASE_ERROR',

  // Configuration (50x)
  CONFIG_MISSING = 'CONFIG_MISSING',
  CONFIG_INVALID = 'CONFIG_INVALID',
}

/**
 * Map error codes to HTTP status codes
 */
export const ErrorCodeToHttpStatus: Record<ErrorCode, number> = {
  // 401 Unauthorized
  [ErrorCode.INVALID_CREDENTIALS]: 401,
  [ErrorCode.TOKEN_EXPIRED]: 401,
  [ErrorCode.TOKEN_INVALID]: 401,
  [ErrorCode.TOKEN_REVOKED]: 401,
  [ErrorCode.UNAUTHORIZED]: 401,

  // 403 Forbidden
  [ErrorCode.EMAIL_NOT_VERIFIED]: 403,
  [ErrorCode.INSUFFICIENT_PERMISSIONS]: 403,
  [ErrorCode.FORBIDDEN]: 403,
  [ErrorCode.USER_BLOCKED]: 403,
  [ErrorCode.MENTOR_NOT_APPROVED]: 403,
  [ErrorCode.ACTION_NOT_ALLOWED]: 403,

  // 404 Not Found
  [ErrorCode.USER_NOT_FOUND]: 404,
  [ErrorCode.RESOURCE_NOT_FOUND]: 404,
  [ErrorCode.MENTOR_NOT_FOUND]: 404,
  [ErrorCode.ADMIN_NOT_FOUND]: 404,

  // 409 Conflict
  [ErrorCode.RESOURCE_ALREADY_EXISTS]: 409,
  [ErrorCode.RESOURCE_CONFLICT]: 409,
  [ErrorCode.USER_ALREADY_EXISTS]: 409,

  // 400 Bad Request
  [ErrorCode.VALIDATION_ERROR]: 400,
  [ErrorCode.VALIDATION_FAILED]: 400,
  [ErrorCode.INVALID_EMAIL]: 400,
  [ErrorCode.INVALID_PASSWORD]: 400,
  [ErrorCode.INVALID_ID_FORMAT]: 400,
  [ErrorCode.INVALID_OPERATION]: 400,

  // 429 Too Many Requests
  [ErrorCode.TOO_MANY_REQUESTS]: 429,
  [ErrorCode.RATE_LIMIT_EXCEEDED]: 429,

  // 500 Internal Server Error
  [ErrorCode.OPERATION_FAILED]: 500,
  [ErrorCode.EMAIL_SERVICE_FAILED]: 500,
  [ErrorCode.FILE_UPLOAD_FAILED]: 500,
  [ErrorCode.DATABASE_ERROR]: 500,
  [ErrorCode.INTERNAL_SERVER_ERROR]: 500,
  [ErrorCode.CONFIG_MISSING]: 500,
  [ErrorCode.CONFIG_INVALID]: 500,

  // 502 Bad Gateway
  [ErrorCode.EXTERNAL_SERVICE_ERROR]: 502,

  // 503 Service Unavailable
  [ErrorCode.SERVICE_UNAVAILABLE]: 503,
};
